### PR TITLE
Automatically generate pyi stubs for built extensions

### LINKED ISSUE #1: Generate .pyi files for all generated modules
This will improve our user experience significantly.

Much of the work for extracting appropriate annotations has actually already been done in the pybind11 for robotpy-rev (which these hooks/templates were derived from). I had removed them because I mistakenly assumed we would only need them for generating sim backends.

### PR DESCRIPTION
**Pull request by virtuald**
- Fixes #1

... I haven't really tried this yet with anything other than the demo, so YMMV.

### CODE REVIEW

**Comment by virtuald** [comment]
Sad, fails on OSX because of relinking related issues.

**Comment by virtuald** [comment]
Looks like the std::function in `hal.simulation` are getting misinterpreted?

```
    def registerFPGAButtonCallback(self, callback: std::function<void (wpi::StringRef, HAL_Value const*)>, initialNotify: bool) -> CallbackStore: 
        """
        registerFPGAButtonCallback(self: hal.simulation._simulation.RoboRioSim, callback: std::function<void (wpi::StringRef, HAL_Value const*)>, initialNotify: bool) -> hal.simulation._simulation.CallbackStore
        """
```

Actually, looks like none of those include `<pybind11/functional.h>` for some reason, so that's probably it.

**Comment by virtuald** [comment]
Filed a bug about this at the stubgen repo: https://github.com/sizmailov/pybind11-stubgen/issues/33

**Comment by virtuald** [comment]
Fixed OSX with this latest push. Newest version of pybind11-stubgen now complains about invalid stubs, so that makes them easier to find. However, there's a lot of them... :(

**Comment by virtuald** [comment]
Looks like it's failing on Windows, the error was getting ignored previously. :(

**Comment by virtuald** [comment]
Say @TheTripleV , any chance you can take a look at this Windows issue... :-D

**Comment by TheTripleV** [comment]
Sure, do I just pick a robotpy repo and build it using this branch of rpybuild?

**Comment by virtuald** [comment]
The github actions for this repo fail, so that should be sufficient. tests/run_tests.py I think.

**Comment by virtuald** [comment]
Looks like it only fails on Python 3.8?

**Comment by TheTripleV** [comment]
`InvalidSignatureInDocstring` has been removed from pybind11-stubgen as of v0.7.0.

**Comment by virtuald** [comment]
Upgraded to latest stubgen.

**Comment by virtuald** [comment]
wtf black

**Comment by virtuald** [comment]
Currently blocked on:

* Windows bug in CI
* https://github.com/sizmailov/pybind11-stubgen/issues/44

**Comment by TheTripleV** [comment]
Huh, the Ubuntu ci failed exactly where the Windows 3.8 one did.

**Pull request merged**
