### PR TITLE
Fix py.typed location

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by auscompgeek** [comment]
So this works, but is there a better way of achieving this?

**Comment by virtuald** [comment]
It feels like there should be a py.typed put next to each pyi file instead? Otherwise you're indicating that the entire package is typed, which isn't true.

**Comment by auscompgeek** [comment]
Teams will be using our libraries with paths like `wpilib.TimedRobot`. If we only put the py.typed next to the pyi (which would be in `wpilib._wpilib`), that won't be covered.

**Comment by virtuald** [comment]
the pyi isn't going to be used directly for that, it would be used for the underlying location?

**Pull request merged**
