### PR TITLE
Add helpful error if a user tries to install an rpy package on an Unsupported Platform

### PR DESCRIPTION
**Pull request by TheTripleV**
Example config in pyproject.toml:
```toml
[tool.robotpy-build]
base_package = "rev"
unsupported_platforms = [
    { os = "osx" },
    { os = "windows", arch = "x86" }
]
```

Example error messages:
{ os = "osx" }:
    "OSError: robotpy-rev is not supported on macOS!"
{ os = "windows", arch = "x86" }:
    "OSError: robotpy-rev is not supported on 32-bit windows!"
{ arch = "x86" }:
    "OSError: robotpy-rev is not supported on 32-bit versions of Python!"

### CODE REVIEW

**Comment by virtuald** [comment]
Thank you for doing this. I would rather the following:

* Use a whitelist of known supported platforms instead
* Try to download anyways just in case, and if it fails, then output the unsupported platform error

**Comment by auscompgeek** [comment]
I agree, a whitelist for binary downloads probably makes more sense given that info is available in the vendordep JSON. Bonus points if we can just copy-paste straight from the JSON.

**Comment by TheTripleV** [comment]
I changed the blacklist into a whitelist. It does not try to download anyways.

Example config in pyproject.toml:

[tool.robotpy-build]
base_package = "rev"
supported_platforms = [
    { os = "linux", arch = "x86-64" },
    { os = "linux", arch = "athena" },
    { os = "windows", arch = "x86-64" },
]
Example error messages:
"OSError: robotpy-rev is not supported on macOS!"
"OSError: robotpy-rev is not supported on 32-bit windows!"
"OSError: robotpy-rev is not supported on 32-bit linux!"

**Comment by TheTripleV** [comment]
Ok. I'll get on that when I get a chance. I think I'll need to catch errors directly from build_dl so I can differentiate between 404 errors and failed downloads.

**Comment by TheTripleV** [comment]
I moved the logic from setup.py into wrapper.py. It now always tries to download.

The flow now is:
- Always try to download
- If it fails and the error is an http 404 and the platform is unsupported, then offer a useful message

**Pull request merged**
